-- Semilla principal gestionada por DataSeeder.java para generar hashes BCrypt.
-- Cuentas: juan.perez@email.com / paciente123, carlos.mendoza@piedrazul.com / agendador123,
-- admin@piedrazul.com / admin123.
